{"version":3,"sources":["components/counter.jsx","components/ErrorBoundary.jsx","App.jsx","index.js"],"names":["Counter","React","useState","counter","setCounter","Error","style","border","marginBottom","padding","maxWidth","onClick","ErrorBoundary","state","hasError","error","infoError","console","log","componentStack","this","props","children","Component","App","textAlign","ReactDOM","render","document","getElementById"],"mappings":"qLA4BeA,EA1BC,WAAO,IAAD,EACUC,IAAMC,SAAS,GADzB,mBACbC,EADa,KACJC,EADI,KAOpB,GAAgB,IAAZD,EACF,MAAM,IAAIE,MAAM,0BAGlB,OACE,yBACEC,MAAO,CACLC,OAAQ,kBACRC,aAAc,QACdC,QAAS,SACTC,SAAU,UAGZ,2BAAIP,GACJ,4BAAQQ,QAlBQ,WAClBP,EAAWD,EAAU,KAiBnB,O,4BCSSS,E,4MA7BbC,MAAQ,CACNC,UAAU,G,gEAQMC,EAAOC,GAEvBC,QAAQC,IAAI,0DAAiDH,GAC7DE,QAAQC,IACN,+DACAF,EAAUG,kB,+BAQZ,OAFqBC,KAAKP,MAAlBC,SAGC,qDAEFM,KAAKC,MAAMC,Y,kDAnBlB,MAAO,CAAER,UAAU,O,GAPKb,IAAMsB,WCuBnBC,EApBH,kBACV,oCACE,4BAAQlB,MAAO,CAAEmB,UAAW,WAC1B,oEAEF,kBAAC,EAAD,KACE,2EACA,kBAAC,EAAD,OAEF,6BACA,uFACA,kBAAC,EAAD,KACE,kBAAC,EAAD,OAEF,kBAAC,EAAD,KACE,kBAAC,EAAD,SCfNC,IAASC,OAAO,kBAAC,EAAD,MAASC,SAASC,eAAe,S","file":"static/js/main.28fb579e.chunk.js","sourcesContent":["import React from \"react\";\n\nconst Counter = () => {\n  const [counter, setCounter] = React.useState(0);\n\n  const handleClick = () => {\n    setCounter(counter + 1);\n  };\n\n  if (counter === 3) {\n    throw new Error(\"Opss ocurrio un error!\");\n  }\n\n  return (\n    <div\n      style={{\n        border: \"1px solid black\",\n        marginBottom: \"1.5em\",\n        padding: \"0.5rem\",\n        maxWidth: \"15rem\",\n      }}\n    >\n      <p>{counter}</p>\n      <button onClick={handleClick}>+</button>\n    </div>\n  );\n};\n\nexport default Counter;\n","import React from \"react\";\n\nclass ErrorBoundary extends React.Component {\n  state = {\n    hasError: false,\n  };\n\n  static getDerivedStateFromError() {\n    // retorna una actualizaci√≥n del estado\n    return { hasError: true };\n  }\n\n  componentDidCatch(error, infoError) {\n    // podemos usar sentry para hacer el registro de errores\n    console.log(\"ErrorBoundary -> componentDidCatch -> errorüö´\", error);\n    console.log(\n      \"ErrorBoundary -> componentDidCatch -> infoError ‚ö†Ô∏è\",\n      infoError.componentStack\n    );\n  }\n\n  render() {\n    // destructuring\n    const { hasError } = this.state;\n\n    if (hasError) {\n      return <p>Opss Ocurrio un error!</p>;\n    }\n    return this.props.children;\n  }\n}\n\nexport default ErrorBoundary;\n","import React from \"react\";\n\nimport Counter from \"./components/counter\";\nimport ErrorBoundary from \"./components/ErrorBoundary\";\n\nconst App = () => (\n  <>\n    <header style={{ textAlign: \"center\" }}>\n      <h1>Error Boundary / L√≠mite de error</h1>\n    </header>\n    <ErrorBoundary>\n      <p>Componentes encerrados en un limite de error</p>\n      <Counter />\n    </ErrorBoundary>\n    <hr />\n    <p>Componentes indepedientes cada uno en un limite de error</p>\n    <ErrorBoundary>\n      <Counter />\n    </ErrorBoundary>\n    <ErrorBoundary>\n      <Counter />\n    </ErrorBoundary>\n  </>\n);\n\nexport default App;\n","import React from \"react\";\nimport ReactDOM from \"react-dom\";\n\nimport App from \"./App\";\n\nReactDOM.render(<App />, document.getElementById(\"wil\"));\n"],"sourceRoot":""}